name: ifsquizz
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.2+2

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  cloud_firestore: ^3.5.1
  firebase_auth: ^3.11.2
  dynamic_color: ^1.5.4
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.2.1
  google_sign_in: ^5.4.2
  sign_in_with_apple: ^4.1.0
  crypto: ^3.0.2
  json_annotation: ^4.7.0
  rxdart: ^0.27.5
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.3.0
  json_serializable: ^6.5.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/covers/
    - assets/congrats.gif
